@baseUrl = "http://js-post-api.herokuapp.com/api"

# Students

# @name getAllStudents
GET {{baseUrl}}/students?_page=16&_limit=10&_sort=mark&_order=desc

###

# @name getStudentById
GET {{baseUrl}}/students/u6V7vww

###

# @name addNewStudent
POST {{baseUrl}}/students
Content-Type: application/json

{
    "name": "Michale",
    "age" : "30",
    "mark" : 10,
    "gender": "male",
    "city" : "pt"
}

###

# @name updateStudent
PATCH {{baseUrl}}/students/u6V7vww
Content-Type: application/json

{
    "name": "Jack"
}

###

# @name removeStudent
DELETE {{baseUrl}}/students/u6V7vww
